//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_Users_Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aspnet_Users_Test()
        {
            this.aspnet_PersonalizationPerUser_Test = new HashSet<aspnet_PersonalizationPerUser_Test>();
            this.stats_PageRequests_Test = new HashSet<stats_PageRequests_Test>();
            this.subs_Adjustments_Test = new HashSet<subs_Adjustments_Test>();
            this.subs_CheckPayments_Test = new HashSet<subs_CheckPayments_Test>();
            this.subs_Gaps_Test = new HashSet<subs_Gaps_Test>();
            this.subs_PayPalPayments_Test = new HashSet<subs_PayPalPayments_Test>();
            this.subs_Trials_Test = new HashSet<subs_Trials_Test>();
            this.users_EmailConfirmations_Test = new HashSet<users_EmailConfirmations_Test>();
            this.site_IPTrackedEvents_Test = new HashSet<site_IPTrackedEvents_Test>();
            this.users_PasswordConfirmations_Test = new HashSet<users_PasswordConfirmations_Test>();
            this.users_Settings_Test = new HashSet<users_Settings_Test>();
            this.aspnet_Roles_Test = new HashSet<aspnet_Roles_Test>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string LoweredUserName { get; set; }
        public string MobileAlias { get; set; }
        public bool IsAnonymous { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public string EULA_Ver { get; set; }
        public Nullable<System.DateTime> EULA_Date { get; set; }
    
        public virtual aspnet_Applications_Test aspnet_Applications_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_PersonalizationPerUser_Test> aspnet_PersonalizationPerUser_Test { get; set; }
        public virtual aspnet_Profile_Test aspnet_Profile_Test { get; set; }
        public virtual clinipro_Users_Test clinipro_Users_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stats_PageRequests_Test> stats_PageRequests_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subs_Adjustments_Test> subs_Adjustments_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subs_CheckPayments_Test> subs_CheckPayments_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subs_Gaps_Test> subs_Gaps_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subs_PayPalPayments_Test> subs_PayPalPayments_Test { get; set; }
        public virtual subs_Subscriptions_Test subs_Subscriptions_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subs_Trials_Test> subs_Trials_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users_EmailConfirmations_Test> users_EmailConfirmations_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<site_IPTrackedEvents_Test> site_IPTrackedEvents_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users_PasswordConfirmations_Test> users_PasswordConfirmations_Test { get; set; }
        public virtual users_Sessions_Test users_Sessions_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users_Settings_Test> users_Settings_Test { get; set; }
        public virtual users_SmarterMailAccounts_Test users_SmarterMailAccounts_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_Roles_Test> aspnet_Roles_Test { get; set; }
    }
}
