//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class help_Images
    {
        public long ImageId { get; set; }
        public string SiteVersion { get; set; }
        public string Page { get; set; }
        public string Module { get; set; }
        public string Name { get; set; }
    
        public virtual help_ImageData help_ImageData { get; set; }
    }
}
