//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class help_ModuleOrder_Test
    {
        public long ModuleOrderId { get; set; }
        public long ModuleId { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual help_Modules_Test help_Modules_Test { get; set; }
    }
}
