//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class insulet_People
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public insulet_People()
        {
            this.insulet_PeopleLocations = new HashSet<insulet_PeopleLocations>();
            this.insulet_PeopleRegions = new HashSet<insulet_PeopleRegions>();
        }
    
        public long PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool KeyAccount { get; set; }
        public long RoleId { get; set; }
        public System.DateTime StartDate { get; set; }
    
        public virtual insulet_PeopleRoles insulet_PeopleRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insulet_PeopleLocations> insulet_PeopleLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insulet_PeopleRegions> insulet_PeopleRegions { get; set; }
    }
}
