//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class insulet_People_Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public insulet_People_Test()
        {
            this.insulet_PeopleLocations_Test = new HashSet<insulet_PeopleLocations_Test>();
            this.insulet_PeopleRegions_Test = new HashSet<insulet_PeopleRegions_Test>();
        }
    
        public long PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool KeyAccount { get; set; }
        public long RoleId { get; set; }
        public System.DateTime StartDate { get; set; }
    
        public virtual insulet_PeopleRoles_Test insulet_PeopleRoles_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insulet_PeopleLocations_Test> insulet_PeopleLocations_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insulet_PeopleRegions_Test> insulet_PeopleRegions_Test { get; set; }
    }
}
