//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class insulet_LocationRegions
    {
        public long EntryId { get; set; }
        public System.Guid LocationId { get; set; }
        public long RegionId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual insulet_Regions insulet_Regions { get; set; }
    }
}
