//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locations_Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locations_Test()
        {
            this.insulet_LocationRegions_Test = new HashSet<insulet_LocationRegions_Test>();
            this.insulet_PeopleLocations_Test = new HashSet<insulet_PeopleLocations_Test>();
            this.insulet_Reports_Test = new HashSet<insulet_Reports_Test>();
        }
    
        public System.Guid LocationId { get; set; }
        public System.Guid Parent_Site { get; set; }
        public string Location_Name { get; set; }
        public Nullable<int> CPSiteId { get; set; }
        public string ConnName { get; set; }
        public string LibIP { get; set; }
        public Nullable<int> LibPort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insulet_LocationRegions_Test> insulet_LocationRegions_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insulet_PeopleLocations_Test> insulet_PeopleLocations_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insulet_Reports_Test> insulet_Reports_Test { get; set; }
        public virtual Sites_Test Sites_Test { get; set; }
    }
}
