//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.insulet_LocationRegions = new HashSet<insulet_LocationRegions>();
            this.insulet_Reports = new HashSet<insulet_Reports>();
        }
    
        public System.Guid LocationId { get; set; }
        public System.Guid Parent_Site { get; set; }
        public string Location_Name { get; set; }
        public Nullable<int> CPSiteId { get; set; }
        public string ConnName { get; set; }
        public string LibIP { get; set; }
        public Nullable<int> LibPort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insulet_LocationRegions> insulet_LocationRegions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insulet_Reports> insulet_Reports { get; set; }
        public virtual Site Site { get; set; }
    }
}
