//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPP_Logins
    {
        public string Username { get; set; }
        public System.DateTime Last_activity { get; set; }
        public Nullable<System.DateTime> Logged_in { get; set; }
        public Nullable<System.DateTime> Created_on { get; set; }
        public string E_mail { get; set; }
        public string CliniProID { get; set; }
        public Nullable<System.DateTime> Expiration_date { get; set; }
        public Nullable<int> Months_paid { get; set; }
        public string Site { get; set; }
        public Nullable<bool> FreeUser { get; set; }
    }
}
