//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy_Docs_Test
    {
        public System.Guid PolicyDocId { get; set; }
        public System.Guid Parent_Corp { get; set; }
        public string DocType { get; set; }
        public string DocText { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Corporations_Test Corporations_Test { get; set; }
    }
}
