//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class subs_PayPalPayments
    {
        public long PayPalPaymentId { get; set; }
        public string txn_id { get; set; }
        public string parent_txn_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public string payment_status { get; set; }
        public string pending_reason { get; set; }
        public string reason_code { get; set; }
        public decimal mc_gross { get; set; }
        public decimal mc_fee { get; set; }
        public string PayPal_post_vars { get; set; }
        public string Notes { get; set; }
        public short MonthsPurchased { get; set; }
        public string SourceIP { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime Date { get; set; }
        public bool SubscriptionTimeApplied { get; set; }
        public System.Guid AddedBy { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
