//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1_Test
    {
        public int IntCol { get; set; }
        public string Col2 { get; set; }
        public Nullable<System.Guid> TableID { get; set; }
        public string Col3 { get; set; }
        public Nullable<int> Col4 { get; set; }
    }
}
