//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.Test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_EmailConfirmations_Test
    {
        public long EmailConfirmationId { get; set; }
        public System.Guid UserId { get; set; }
        public string Email { get; set; }
        public string LoweredEmail { get; set; }
        public long ConfirmationCode { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> ConfirmedOn { get; set; }
    
        public virtual aspnet_Users_Test aspnet_Users_Test { get; set; }
    }
}
