//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AspnetDbEntities : DbContext
    {
        public AspnetDbEntities()
            : base("name=AspnetDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FirebirdConnection> FirebirdConnections { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<clinipro_Users> clinipro_Users { get; set; }
        public virtual DbSet<CorporationsView> CorporationsViews { get; set; }
        public virtual DbSet<subs_Adjustments> subs_Adjustments { get; set; }
        public virtual DbSet<subs_CheckPayments> subs_CheckPayments { get; set; }
        public virtual DbSet<subs_Gaps> subs_Gaps { get; set; }
        public virtual DbSet<subs_PayPalPayments> subs_PayPalPayments { get; set; }
        public virtual DbSet<subs_Subscriptions> subs_Subscriptions { get; set; }
        public virtual DbSet<subs_Trials> subs_Trials { get; set; }
    }
}
