//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasalDelivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BasalDelivery()
        {
            this.BasalDeliveryDatas = new HashSet<BasalDeliveryData>();
        }
    
        public int BasalDeliveryId { get; set; }
        public int AmountDelivered { get; set; }
        public double DeliveryRate { get; set; }
        public bool IsTemp { get; set; }
        public string Duration { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.Guid ReadingKeyId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual ReadingHeader ReadingHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasalDeliveryData> BasalDeliveryDatas { get; set; }
    }
}
