//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BGTarget
    {
        public int TargetId { get; set; }
        public int TargetBG { get; set; }
        public int TargetBGCorrect { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual BolusDelivery BolusDelivery { get; set; }
    }
}
