//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BolusDelivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BolusDelivery()
        {
            this.BolusDeliveryDatas = new HashSet<BolusDeliveryData>();
        }
    
        public int BolusDeliveryId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public int AmountDelivered { get; set; }
        public int AmountSuggested { get; set; }
        public int Duration { get; set; }
        public string BolusTrigger { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public System.Guid ReadingKeyId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual BGTarget BGTarget { get; set; }
        public virtual ReadingHeader ReadingHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolusDeliveryData> BolusDeliveryDatas { get; set; }
        public virtual CorrectionFactor CorrectionFactor { get; set; }
        public virtual InsulinCarbRatio InsulinCarbRatio { get; set; }
        public virtual InsulinCorrection InsulinCorrection { get; set; }
    }
}
