//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CareSetting()
        {
            this.DailyTimeSlots = new HashSet<DailyTimeSlot>();
            this.DiabetesControlTypes = new HashSet<DiabetesControlType>();
        }
    
        public int CareSettingsId { get; set; }
        public string PatientId { get; set; }
        public int HyperglycemicLevel { get; set; }
        public int HypoglycemicLevel { get; set; }
        public int InsulinMethod { get; set; }
        public int DiabetesManagementType { get; set; }
        public int InsulinBrand { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyTimeSlot> DailyTimeSlots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiabetesControlType> DiabetesControlTypes { get; set; }
    }
}
