//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClientDatabaseTemplateEntities : DbContext
    {
        public ClientDatabaseTemplateEntities()
            : base("name=ClientDatabaseTemplateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasalProgramTimeSlot> BasalProgramTimeSlots { get; set; }
        public virtual DbSet<BolusDelivery> BolusDeliveries { get; set; }
        public virtual DbSet<BolusDeliveryData> BolusDeliveryDatas { get; set; }
        public virtual DbSet<BolusProgramTimeSlot> BolusProgramTimeSlots { get; set; }
        public virtual DbSet<CareSetting> CareSettings { get; set; }
        public virtual DbSet<CGMReminder> CGMReminders { get; set; }
        public virtual DbSet<CGMSession> CGMSessions { get; set; }
        public virtual DbSet<DailyTimeSlot> DailyTimeSlots { get; set; }
        public virtual DbSet<DatabaseInfo> DatabaseInfoes { get; set; }
        public virtual DbSet<DeviceData> DeviceDatas { get; set; }
        public virtual DbSet<DiabetesControlType> DiabetesControlTypes { get; set; }
        public virtual DbSet<DiabetesManagementData> DiabetesManagementDatas { get; set; }
        public virtual DbSet<InsuranceAddress> InsuranceAddresses { get; set; }
        public virtual DbSet<InsuranceContact> InsuranceContacts { get; set; }
        public virtual DbSet<InsurancePlan> InsurancePlans { get; set; }
        public virtual DbSet<InsuranceProvider> InsuranceProviders { get; set; }
        public virtual DbSet<MeterReadingError> MeterReadingErrors { get; set; }
        public virtual DbSet<MeterReadingEvent> MeterReadingEvents { get; set; }
        public virtual DbSet<MeterReadingHeader> MeterReadingHeaders { get; set; }
        public virtual DbSet<MeterReading> MeterReadings { get; set; }
        public virtual DbSet<PatientAddress> PatientAddresses { get; set; }
        public virtual DbSet<PatientDevice> PatientDevices { get; set; }
        public virtual DbSet<PatientEmail> PatientEmails { get; set; }
        public virtual DbSet<PatientPhoneNumber> PatientPhoneNumbers { get; set; }
        public virtual DbSet<PatientPhoto> PatientPhotos { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PumpBGTarget> PumpBGTargets { get; set; }
        public virtual DbSet<PumpCorrectionFactor> PumpCorrectionFactors { get; set; }
        public virtual DbSet<PumpInsulinCorrection> PumpInsulinCorrections { get; set; }
        public virtual DbSet<PumpProgram> PumpPrograms { get; set; }
        public virtual DbSet<Pump> Pumps { get; set; }
        public virtual DbSet<PumpSetting> PumpSettings { get; set; }
        public virtual DbSet<TotalDailyDelivery> TotalDailyDeliveries { get; set; }
        public virtual DbSet<InsulinBrand> InsulinBrands { get; set; }
        public virtual DbSet<InsulinMethod> InsulinMethods { get; set; }
        public virtual DbSet<DiabetesManagementType> DiabetesManagementTypes { get; set; }
    }
}
