//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinician
    {
        public System.Guid UserId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string StateLicenseNumber { get; set; }
        public System.Guid InstitutionId { get; set; }
        public System.Guid LastUpdatedByUser { get; set; }
    
        public virtual Institution Institution { get; set; }
        public virtual User User { get; set; }
    }
}
