//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporationsView
    {
        public string Corp_Name { get; set; }
        public string Site_Name { get; set; }
        public string Location_Name { get; set; }
        public string DatabaseLocation { get; set; }
        public string DatasourceServer { get; set; }
        public int Port { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string SiteName { get; set; }
        public string Location { get; set; }
    }
}
