//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataShareRequestLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataShareRequestLog()
        {
            this.SharedAreas = new HashSet<SharedArea>();
        }
    
        public int RequestId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public System.Guid ApplicationId { get; set; }
        public System.Guid PatientId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SharedArea> SharedAreas { get; set; }
    }
}
