//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_UserAuthentications_CT
    {
        public byte[] C___start_lsn { get; set; }
        public byte[] C___end_lsn { get; set; }
        public byte[] C___seqval { get; set; }
        public int C___operation { get; set; }
        public byte[] C___update_mask { get; set; }
        public Nullable<int> AuthenticationId { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public Nullable<int> PasswordFailureCount { get; set; }
        public Nullable<int> PasswordAnswerFailureCount { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.DateTime> LastLockOutDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<bool> IsTempPassword { get; set; }
        public Nullable<bool> IsloggedIn { get; set; }
        public string NotApprovedReason { get; set; }
        public Nullable<System.Guid> LastUpdatedByUser { get; set; }
    }
}
