//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_CareSettings_CT
    {
        public byte[] C___start_lsn { get; set; }
        public byte[] C___end_lsn { get; set; }
        public byte[] C___seqval { get; set; }
        public int C___operation { get; set; }
        public byte[] C___update_mask { get; set; }
        public Nullable<int> CareSettingsId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> HyperglycemicLevel { get; set; }
        public Nullable<int> HypoglycemicLevel { get; set; }
        public Nullable<int> InsulinMethod { get; set; }
        public Nullable<int> DiabetesManagementType { get; set; }
        public Nullable<int> InsulinBrand { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.Guid> LastUpdatedByUser { get; set; }
    }
}
