//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_InsurancePlans_CT
    {
        public byte[] C___start_lsn { get; set; }
        public byte[] C___end_lsn { get; set; }
        public byte[] C___seqval { get; set; }
        public int C___operation { get; set; }
        public byte[] C___update_mask { get; set; }
        public Nullable<int> PlanId { get; set; }
        public string PlanType { get; set; }
        public string PlanIdentifier { get; set; }
        public string PolicyNumber { get; set; }
        public string GroupName { get; set; }
        public string GroupIdentifier { get; set; }
        public Nullable<decimal> CoPay { get; set; }
        public string Purchaser { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string PlanName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> LastUpdatedByUser { get; set; }
    }
}
