//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiabetesManagementData
    {
        public int DMDataId { get; set; }
        public int LowBGLevel { get; set; }
        public int HighBGLevel { get; set; }
        public int PremealTarget { get; set; }
        public int PostmealTarget { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid ModifiedUserId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual PatientDevice PatientDevice { get; set; }
    }
}
