//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiabetesManagementData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiabetesManagementData()
        {
            this.DiabetesControlTypes = new HashSet<DiabetesControlType>();
        }
    
        public int DMDataId { get; set; }
        public int LowBGLevel { get; set; }
        public int HighBGLevel { get; set; }
        public int HyperglycemicLevel { get; set; }
        public int HypoglycemicLevel { get; set; }
        public int InsulinMethod { get; set; }
        public int DiabetesManagementType { get; set; }
        public int InsulinBrand { get; set; }
        public int PremealTarget { get; set; }
        public int PostmealTarget { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid ModifiedUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiabetesControlType> DiabetesControlTypes { get; set; }
        public virtual PatientDevice PatientDevice { get; set; }
    }
}
