//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsurancePlan()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public int PlanId { get; set; }
        public string PlanType { get; set; }
        public string PlanIdentifier { get; set; }
        public string PolicyNumber { get; set; }
        public string GroupName { get; set; }
        public string GroupIdentifier { get; set; }
        public decimal CoPay { get; set; }
        public string Purchaser { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime InActiveDate { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public string PlanName { get; set; }
        public int CompanyId { get; set; }
        public string PatientId { get; set; }
    
        public virtual InsuranceProvider InsuranceProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
