//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecordIdentifier
    {
        public int Id { get; set; }
        public System.Guid PatientUserId { get; set; }
        public string MRID { get; set; }
        public System.Guid InstitutionId { get; set; }
    
        public virtual Institution Institution { get; set; }
    }
}
