//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReadingError
    {
        public int ErrorId { get; set; }
        public string ErrorName { get; set; }
        public bool IsActive { get; set; }
        public int ReadingId { get; set; }
        public string ErrorText { get; set; }
    
        public virtual MeterReading MeterReading { get; set; }
    }
}
