//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientListView
    {
        public System.Guid InstitutionId { get; set; }
        public System.Guid UserId { get; set; }
        public string Username { get; set; }
        public string InstitutionName { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Middlename { get; set; }
        public string Email { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string MRID { get; set; }
    }
}
