//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedication
    {
        public string Name { get; set; }
        public long MedicationId { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int HourlyDosageInterval { get; set; }
        public int DosageTakenDaily { get; set; }
        public System.Guid UserId { get; set; }
        public int PatientMedicationId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
