//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientDevice()
        {
            this.ReadingHeaders = new HashSet<ReadingHeader>();
        }
    
        public int DeviceId { get; set; }
        public System.Guid UserId { get; set; }
        public int MeterIndex { get; set; }
        public string Manufacturer { get; set; }
        public string DeviceModel { get; set; }
        public string DeviceName { get; set; }
        public string SerialNumber { get; set; }
        public string SoftwareVersion { get; set; }
        public string HardwareVersion { get; set; }
        public bool IsCGMData { get; set; }
    
        public virtual DeviceData DeviceData { get; set; }
        public virtual DiabetesManagementData DiabetesManagementData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadingHeader> ReadingHeaders { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
