//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientLinkLog
    {
        public int LinkId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid InstitutionId { get; set; }
        public System.DateTime LinkCreationDate { get; set; }
        public System.DateTime LinkSeverDate { get; set; }
        public bool HasFreeDownload { get; set; }
    }
}
