//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysiologicalReading
    {
        public int ReadingId { get; set; }
        public System.DateTime Time { get; set; }
        public int Weight { get; set; }
        public int Height { get; set; }
        public int Hunger { get; set; }
        public int Nausea { get; set; }
        public int CaloriesBurned { get; set; }
        public int CaloriesConsumed { get; set; }
        public string Notes { get; set; }
        public System.Guid ReadingKeyId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual ReadingHeader ReadingHeader { get; set; }
    }
}
