//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PumpInsulinCorrection
    {
        public int CorrectionId { get; set; }
        public int InsulinCorrectionValue { get; set; }
        public System.TimeSpan InsulinCorrectionStart { get; set; }
        public System.TimeSpan InsulinCorrectionStop { get; set; }
        public int PumpId { get; set; }
    
        public virtual Pump Pump { get; set; }
    }
}
