//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pump
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pump()
        {
            this.PumpPrograms = new HashSet<PumpProgram>();
            this.PumpSettings = new HashSet<PumpSetting>();
        }
    
        public string PumpType { get; set; }
        public string PumpName { get; set; }
        public System.DateTime PumpStartDate { get; set; }
        public string PumpInfusionSet { get; set; }
        public int ActiveProgramId { get; set; }
        public double Cannula { get; set; }
        public System.DateTime ReplacementDate { get; set; }
        public string Notes { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid PumpKeyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PumpProgram> PumpPrograms { get; set; }
        public virtual ReadingHeader ReadingHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PumpSetting> PumpSettings { get; set; }
    }
}
