//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedArea
    {
        public int ShareId { get; set; }
        public int SharedCategoryId { get; set; }
        public int RequestId { get; set; }
    
        public virtual DataShareRequestLog DataShareRequestLog { get; set; }
    }
}
