//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class subs_Gaps
    {
        public long GapId { get; set; }
        public int Days { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime Date { get; set; }
        public bool SubscriptionTimeApplied { get; set; }
        public System.Guid AddedBy { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
