//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionsView
    {
        public int SubscriptionId { get; set; }
        public System.Guid UserId { get; set; }
        public int SubscriptionType { get; set; }
        public System.DateTime SubscriptionDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public bool IsTrial { get; set; }
        public System.Guid ApplicationId { get; set; }
        public int UserType { get; set; }
        public System.Guid InstitutionId { get; set; }
        public int PaymentMethod { get; set; }
        public int PaymentId { get; set; }
        public int CheckId { get; set; }
        public int CheckStatus { get; set; }
        public string CheckNumber { get; set; }
        public long CheckCode { get; set; }
        public System.DateTime CheckDateRecieved { get; set; }
        public decimal CheckAmount { get; set; }
        public Nullable<int> PayPalId { get; set; }
        public Nullable<System.DateTime> PayPalPaymentDate { get; set; }
        public string PayPalPaymentStatus { get; set; }
        public Nullable<decimal> PayPalPayment { get; set; }
    }
}
