//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int SubscriptionId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public int UserType { get; set; }
        public int SubscriptionType { get; set; }
        public System.DateTime SubscriptionDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    
        public virtual Clinician Clinician { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
