//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class subs_Subscriptions
    {
        public System.Guid UserId { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public byte DayOfPayment { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
