//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalDailyInsulinDelivery
    {
        public int DeliveryId { get; set; }
        public double TotalDelivered { get; set; }
        public double BasalDelivered { get; set; }
        public Nullable<bool> Suspended { get; set; }
        public bool TempActivated { get; set; }
        public bool Valid { get; set; }
        public double BolusDelivered { get; set; }
        public System.Guid ReadingKeyId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual ReadingHeader ReadingHeader { get; set; }
    }
}
