//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuLibrary.Migration.SQLDatabase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthentication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAuthentication()
        {
            this.PasswordHistories = new HashSet<PasswordHistory>();
        }
    
        public int AuthenticationId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public int PasswordFailureCount { get; set; }
        public int PasswordAnswerFailureCount { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public System.DateTime LastLockOutDate { get; set; }
        public bool IsApproved { get; set; }
        public bool IsLockedOut { get; set; }
        public bool IsTempPassword { get; set; }
        public bool IsloggedIn { get; set; }
        public string NotApprovedReason { get; set; }
    
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PasswordHistory> PasswordHistories { get; set; }
        public virtual User User { get; set; }
    }
}
